import { db } from './index';
import {
  users,
  patients,
  doctors,
  appointments,
  prescriptions,
  labReports,
  invoices,
  inventory,
  beds,
  auditLogs,
  notifications,
  settings,
} from './schema';
import { eq } from 'drizzle-orm';

export async function seedDatabase() {
  try {
    const existingSettings = await db.select().from(settings).where(eq(settings.id, 'default_setting'));
    if (existingSettings.length > 0) {
      // Database already seeded
      return;
    }

    console.log('Seeding Hospital database...');

    // 1. Settings
    await db.insert(settings).values({
      id: 'default_setting',
      hospitalName: 'AegisCare Medical Center & Research Institute',
      registrationNumber: 'HOSP-2026-REG-88910',
      tagline: 'Precision Healthcare Powered by Modern Medical Intelligence',
      phone: '+1 (800) 555-0199',
      email: 'contact@aegiscare-medical.org',
      website: 'https://aegiscare-hospital.org',
      address: '750 Healthcare Blvd, Suite 400, Medical District, NY 10016',
      currencySymbol: '$',
      taxRatePercentage: 5.0,
      opdConsultationValidityDays: 14,
      emergencyContactNumber: '+1 (800) 911-0000',
      enableAiAssistant: true,
      enableNotifications: true,
      themeMode: 'dark',
    });

    // 2. Users
    await db.insert(users).values([
      {
        id: 'usr_admin',
        name: 'Dr. Sarah Connor',
        email: 'admin@aegiscare.org',
        role: 'ADMIN',
        department: 'Hospital Operations & IT',
        phone: '+1 (555) 012-3456',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_doc1',
        name: 'Dr. Alexander Vance',
        email: 'vance@aegiscare.org',
        role: 'DOCTOR',
        department: 'Cardiology',
        phone: '+1 (555) 012-3457',
        avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_doc2',
        name: 'Dr. Elena Rostova',
        email: 'rostova@aegiscare.org',
        role: 'DOCTOR',
        department: 'Neurology',
        phone: '+1 (555) 012-3458',
        avatar: 'https://images.unsplash.com/photo-1594824813566-88824278cc1a?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_nurse',
        name: 'Nurse Clara Oswald',
        email: 'clara@aegiscare.org',
        role: 'NURSE',
        department: 'ICU / Inpatient Ward',
        phone: '+1 (555) 012-3459',
        avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_reception',
        name: 'Michael Scott',
        email: 'reception@aegiscare.org',
        role: 'RECEPTIONIST',
        department: 'Front Desk & Triage',
        phone: '+1 (555) 012-3460',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_pharmacist',
        name: 'David Miller, RPh',
        email: 'pharmacy@aegiscare.org',
        role: 'PHARMACIST',
        department: 'Central Pharmacy',
        phone: '+1 (555) 012-3461',
        avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'usr_labtech',
        name: 'Sophia Patel',
        email: 'lab@aegiscare.org',
        role: 'LAB_TECH',
        department: 'Pathology & Diagnostics',
        phone: '+1 (555) 012-3462',
        avatar: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=250',
      },
    ]);

    // 3. Doctors
    await db.insert(doctors).values([
      {
        id: 'doc_1',
        doctorCode: 'DOC-101',
        fullName: 'Dr. Alexander Vance',
        specialty: 'Interventional Cardiology',
        department: 'Cardiology',
        qualification: 'MD, FACC, FSCAI',
        experienceYears: 16,
        consultationFee: 150.0,
        roomNumber: 'Suite 302',
        phone: '+1 (555) 012-3457',
        email: 'vance@aegiscare.org',
        schedule: {
          days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
          timeSlots: ['09:00 AM', '10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM'],
        },
        status: 'AVAILABLE',
        rating: 4.9,
        avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'doc_2',
        doctorCode: 'DOC-102',
        fullName: 'Dr. Elena Rostova',
        specialty: 'Clinical Neurology & Neuro-Oncology',
        department: 'Neurology',
        qualification: 'MD, PhD, FAAN',
        experienceYears: 12,
        consultationFee: 175.0,
        roomNumber: 'Suite 405',
        phone: '+1 (555) 012-3458',
        email: 'rostova@aegiscare.org',
        schedule: {
          days: ['Mon', 'Wed', 'Thu', 'Sat'],
          timeSlots: ['09:30 AM', '11:00 AM', '01:30 PM', '03:00 PM'],
        },
        status: 'IN_CONSULTATION',
        rating: 4.85,
        avatar: 'https://images.unsplash.com/photo-1594824813566-88824278cc1a?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'doc_3',
        doctorCode: 'DOC-103',
        fullName: 'Dr. Marcus Thorne',
        specialty: 'Orthopedic Surgery & Sports Medicine',
        department: 'Orthopedics',
        qualification: 'MS (Ortho), FRCS',
        experienceYears: 14,
        consultationFee: 140.0,
        roomNumber: 'Suite 201',
        phone: '+1 (555) 012-3490',
        email: 'thorne@aegiscare.org',
        schedule: {
          days: ['Tue', 'Thu', 'Fri'],
          timeSlots: ['10:00 AM', '11:30 AM', '02:30 PM', '04:00 PM'],
        },
        status: 'AVAILABLE',
        rating: 4.92,
        avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=250',
      },
      {
        id: 'doc_4',
        doctorCode: 'DOC-104',
        fullName: 'Dr. Maya Lin',
        specialty: 'Pediatrics & Adolescent Care',
        department: 'Pediatrics',
        qualification: 'MD (Ped), DCH',
        experienceYears: 9,
        consultationFee: 120.0,
        roomNumber: 'Suite 108',
        phone: '+1 (555) 012-3491',
        email: 'lin@aegiscare.org',
        schedule: {
          days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
          timeSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '02:00 PM'],
        },
        status: 'AVAILABLE',
        rating: 4.95,
        avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=250',
      },
    ]);

    // 4. Patients
    await db.insert(patients).values([
      {
        id: 'pat_1',
        patientCode: 'PAT-8001',
        fullName: 'Jonathan Reed',
        dob: '1984-06-15',
        gender: 'Male',
        bloodGroup: 'O+',
        phone: '+1 (555) 234-5678',
        email: 'j.reed@example.com',
        address: '42 Pine Crest Road, Brooklyn, NY',
        emergencyContact: {
          name: 'Sarah Reed',
          relation: 'Spouse',
          phone: '+1 (555) 234-9999',
        },
        insurance: {
          provider: 'Blue Cross Blue Shield',
          policyNumber: 'BCBS-998231',
          coverageLimit: 50000,
          status: 'ACTIVE',
        },
        medicalHistory: ['Hypertension (2020)', 'Hyperlipidemia'],
        allergies: ['Penicillin', 'Sulfa drugs'],
        type: 'OPD',
        createdAt: new Date(),
      },
      {
        id: 'pat_2',
        patientCode: 'PAT-8002',
        fullName: 'Eleanor Vance',
        dob: '1959-11-22',
        gender: 'Female',
        bloodGroup: 'A+',
        phone: '+1 (555) 345-6789',
        email: 'e.vance@example.com',
        address: '112 Maple Avenue, Manhattan, NY',
        emergencyContact: {
          name: 'Robert Vance',
          relation: 'Son',
          phone: '+1 (555) 345-8888',
        },
        insurance: {
          provider: 'Aetna Global Health',
          policyNumber: 'AET-44321',
          coverageLimit: 100000,
          status: 'ACTIVE',
        },
        medicalHistory: ['Type 2 Diabetes', 'Coronary Artery Disease', 'Post-CABG'],
        allergies: ['Aspirin', 'Iodine Contrast'],
        type: 'IPD',
        bedNumber: 'ICU-Bed-02',
        admittedAt: '2026-03-28 08:30',
        createdAt: new Date(),
      },
      {
        id: 'pat_3',
        patientCode: 'PAT-8003',
        fullName: 'Marcus Aurelius Sterling',
        dob: '1992-03-04',
        gender: 'Male',
        bloodGroup: 'B-',
        phone: '+1 (555) 456-7890',
        email: 'm.sterling@example.com',
        address: '88 Tech Boulevard, Queens, NY',
        emergencyContact: {
          name: 'Chloe Sterling',
          relation: 'Sister',
          phone: '+1 (555) 456-0000',
        },
        insurance: {
          provider: 'UnitedHealthcare',
          policyNumber: 'UHC-771120',
          coverageLimit: 25000,
          status: 'ACTIVE',
        },
        medicalHistory: ['Bronchial Asthma'],
        allergies: ['Dust mites', 'NSAIDs'],
        type: 'EMERGENCY',
        bedNumber: 'EMG-Bay-01',
        admittedAt: '2026-03-30 14:15',
        createdAt: new Date(),
      },
      {
        id: 'pat_4',
        patientCode: 'PAT-8004',
        fullName: 'Sophia Martinez',
        dob: '1998-08-19',
        gender: 'Female',
        bloodGroup: 'AB+',
        phone: '+1 (555) 567-8901',
        email: 'smartinez@example.com',
        address: '504 Riverway Lane, Bronx, NY',
        emergencyContact: {
          name: 'Carlos Martinez',
          relation: 'Father',
          phone: '+1 (555) 567-1111',
        },
        insurance: {
          provider: 'Cigna Health',
          policyNumber: 'CGN-552219',
          coverageLimit: 30000,
          status: 'ACTIVE',
        },
        medicalHistory: ['Migraine with aura'],
        allergies: [],
        type: 'OPD',
        createdAt: new Date(),
      },
      {
        id: 'pat_5',
        patientCode: 'PAT-8005',
        fullName: 'Robert Chen',
        dob: '1971-02-10',
        gender: 'Male',
        bloodGroup: 'O-',
        phone: '+1 (555) 678-9012',
        email: 'rchen@example.com',
        address: '19 Grand Street, Staten Island, NY',
        emergencyContact: {
          name: 'Linda Chen',
          relation: 'Wife',
          phone: '+1 (555) 678-2222',
        },
        insurance: {
          provider: 'Kaiser Permanente',
          policyNumber: 'KP-889021',
          coverageLimit: 75000,
          status: 'ACTIVE',
        },
        medicalHistory: ['Lumbar Disc Herniation', 'Hypertension'],
        allergies: ['Codeine'],
        type: 'IPD',
        bedNumber: 'GEN-304',
        admittedAt: '2026-03-29 11:00',
        createdAt: new Date(),
      },
    ]);

    // 5. Appointments
    await db.insert(appointments).values([
      {
        id: 'apt_101',
        appointmentCode: 'APT-2026-101',
        patientId: 'pat_1',
        patientName: 'Jonathan Reed',
        patientPhone: '+1 (555) 234-5678',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        department: 'Cardiology',
        date: '2026-03-30',
        timeSlot: '09:00 AM',
        type: 'OPD Consultation',
        status: 'IN_PROGRESS',
        queueToken: 1,
        reason: 'Follow-up for blood pressure medication adjustment & ECG review',
        vitals: {
          bpSystolic: 138,
          bpDiastolic: 88,
          heartRate: 76,
          temperature: 98.6,
          spO2: 98,
          respiratoryRate: 16,
          weightKg: 82.5,
          heightCm: 178,
          recordedBy: 'Nurse Clara Oswald',
          recordedAt: '2026-03-30 08:45 AM',
        },
      },
      {
        id: 'apt_102',
        appointmentCode: 'APT-2026-102',
        patientId: 'pat_4',
        patientName: 'Sophia Martinez',
        patientPhone: '+1 (555) 567-8901',
        doctorId: 'doc_2',
        doctorName: 'Dr. Elena Rostova',
        department: 'Neurology',
        date: '2026-03-30',
        timeSlot: '11:00 AM',
        type: 'Routine Checkup',
        status: 'CHECKED_IN',
        queueToken: 2,
        reason: 'Recurrent severe temporal headaches with visual aura',
        vitals: {
          bpSystolic: 120,
          bpDiastolic: 78,
          heartRate: 72,
          temperature: 98.4,
          spO2: 99,
          respiratoryRate: 14,
          weightKg: 58.0,
          heightCm: 165,
          recordedBy: 'Michael Scott',
          recordedAt: '2026-03-30 10:30 AM',
        },
      },
      {
        id: 'apt_103',
        appointmentCode: 'APT-2026-103',
        patientId: 'pat_3',
        patientName: 'Marcus Aurelius Sterling',
        patientPhone: '+1 (555) 456-7890',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        department: 'Cardiology',
        date: '2026-03-30',
        timeSlot: '02:00 PM',
        type: 'Emergency Triage',
        status: 'SCHEDULED',
        queueToken: 3,
        reason: 'Acute shortness of breath & atypical chest tightness after exercise',
      },
      {
        id: 'apt_104',
        appointmentCode: 'APT-2026-104',
        patientId: 'pat_5',
        patientName: 'Robert Chen',
        patientPhone: '+1 (555) 678-9012',
        doctorId: 'doc_3',
        doctorName: 'Dr. Marcus Thorne',
        department: 'Orthopedics',
        date: '2026-03-30',
        timeSlot: '03:30 PM',
        type: 'Post-Op Follow-up',
        status: 'SCHEDULED',
        queueToken: 4,
        reason: 'Evaluation of L4-L5 lumbar spine alignment & mobility',
      },
    ]);

    // 6. Prescriptions
    await db.insert(prescriptions).values([
      {
        id: 'rx_101',
        prescriptionCode: 'RX-2026-901',
        appointmentId: 'apt_101',
        patientId: 'pat_1',
        patientName: 'Jonathan Reed',
        patientAgeGender: '41 Yrs / Male',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        diagnosis: 'Stage 1 Essential Hypertension with mild dyslipidemia',
        symptoms: ['Mild occipital morning headaches', 'Occasional exertional fatigue'],
        vitals: {
          bpSystolic: 138,
          bpDiastolic: 88,
          heartRate: 76,
          temperature: 98.6,
          spO2: 98,
          respiratoryRate: 16,
          weightKg: 82.5,
          heightCm: 178,
        },
        medications: [
          {
            medicineName: 'Telmisartan 40mg Tablet',
            dosage: '40 mg',
            frequency: 'Once Daily (Morning)',
            durationDays: 30,
            instructions: 'Take after breakfast with water',
            dispensed: true,
          },
          {
            medicineName: 'Atorvastatin 10mg Tablet',
            dosage: '10 mg',
            frequency: 'Once Daily (At Bedtime)',
            durationDays: 30,
            instructions: 'Take before sleeping',
            dispensed: false,
          },
        ],
        labTestsOrdered: ['Lipid Profile Complete', 'Serum Electrolytes & Creatinine'],
        followUpDate: '2026-04-30',
        aiSafetyCheck: {
          flagged: false,
          warnings: ['Patient has documented Penicillin allergy; no beta-lactam antibiotics prescribed.'],
          summary: 'Medication combination is safe. Renal clearance check recommended before dosage escalation.',
        },
        status: 'PARTIALLY_DISPENSED',
      },
      {
        id: 'rx_102',
        prescriptionCode: 'RX-2026-902',
        patientId: 'pat_2',
        patientName: 'Eleanor Vance',
        patientAgeGender: '66 Yrs / Female',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        diagnosis: 'Post-Coronary Angioplasty Recovery & Heart Failure Management',
        symptoms: ['Ankle edema', 'Bilateral lung crackles', 'Fatigue'],
        vitals: {
          bpSystolic: 110,
          bpDiastolic: 70,
          heartRate: 64,
          temperature: 98.2,
          spO2: 96,
          respiratoryRate: 18,
          weightKg: 64.0,
          heightCm: 160,
        },
        medications: [
          {
            medicineName: 'Clopidogrel 75mg Tablet',
            dosage: '75 mg',
            frequency: 'Once Daily',
            durationDays: 90,
            instructions: 'Antiplatelet therapy - do not skip doses',
            dispensed: true,
          },
          {
            medicineName: 'Furosemide 20mg Tablet',
            dosage: '20 mg',
            frequency: 'Twice Daily',
            durationDays: 14,
            instructions: 'Monitor fluid intake & daily weight',
            dispensed: true,
          },
        ],
        labTestsOrdered: ['Serum Potassium & Sodium Level', 'NT-proBNP Level'],
        followUpDate: '2026-04-10',
        aiSafetyCheck: {
          flagged: true,
          warnings: ['Diuretic co-administration requires daily electrolyte monitor due to arrhythmia risk.'],
          summary: 'Potassium monitoring mandatory.',
        },
        status: 'DISPENSED',
      },
    ]);

    // 7. Lab Reports
    await db.insert(labReports).values([
      {
        id: 'lab_201',
        reportCode: 'LAB-2026-301',
        patientId: 'pat_1',
        patientName: 'Jonathan Reed',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        testName: 'Complete Blood Count (CBC) with Differential',
        testCategory: 'Hematology',
        specimenType: 'Venous Whole Blood (EDTA)',
        collectedAt: '2026-03-30 08:30 AM',
        reportedAt: '2026-03-30 11:15 AM',
        status: 'COMPLETED',
        results: [
          { parameter: 'Hemoglobin (Hb)', value: '14.8', unit: 'g/dL', referenceRange: '13.5 - 17.5', status: 'NORMAL' },
          { parameter: 'White Blood Cell Count (WBC)', value: '7.2', unit: '10^3/µL', referenceRange: '4.5 - 11.0', status: 'NORMAL' },
          { parameter: 'Platelet Count', value: '280', unit: '10^3/µL', referenceRange: '150 - 450', status: 'NORMAL' },
          { parameter: 'Hematocrit (HCT)', value: '44.2', unit: '%', referenceRange: '41.0 - 50.0', status: 'NORMAL' },
        ],
        technicianNotes: 'All hematological parameters within physiological limits.',
        technicianName: 'Sophia Patel',
      },
      {
        id: 'lab_202',
        reportCode: 'LAB-2026-302',
        patientId: 'pat_2',
        patientName: 'Eleanor Vance',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        testName: 'Cardiac Biomarkers & Electrolyte Panel',
        testCategory: 'Biochemistry',
        specimenType: 'Blood Serum',
        collectedAt: '2026-03-30 07:00 AM',
        reportedAt: '2026-03-30 09:30 AM',
        status: 'CRITICAL_ALERT',
        results: [
          { parameter: 'Troponin-I (High Sensitivity)', value: '1.45', unit: 'ng/mL', referenceRange: '< 0.04', status: 'CRITICAL' },
          { parameter: 'Serum Potassium (K+)', value: '3.1', unit: 'mEq/L', referenceRange: '3.5 - 5.1', status: 'LOW' },
          { parameter: 'Serum Creatinine', value: '1.1', unit: 'mg/dL', referenceRange: '0.6 - 1.2', status: 'NORMAL' },
          { parameter: 'NT-proBNP', value: '1850', unit: 'pg/mL', referenceRange: '< 300', status: 'HIGH' },
        ],
        technicianNotes: 'CRITICAL ALERT: Elevated Troponin-I and mild hypokalemia flagged immediately to ICU Doctor on duty.',
        technicianName: 'Sophia Patel',
      },
      {
        id: 'lab_203',
        reportCode: 'LAB-2026-303',
        patientId: 'pat_3',
        patientName: 'Marcus Aurelius Sterling',
        doctorId: 'doc_1',
        doctorName: 'Dr. Alexander Vance',
        testName: 'Arterial Blood Gas (ABG) & D-Dimer',
        testCategory: 'Pulmonary / Emergency',
        specimenType: 'Arterial Blood',
        collectedAt: '2026-03-30 02:20 PM',
        reportedAt: '2026-03-30 02:50 PM',
        status: 'PROCESSING',
        results: [],
        technicianNotes: 'Emergency sample processing under priority status.',
        technicianName: 'Sophia Patel',
      },
    ]);

    // 8. Invoices
    await db.insert(invoices).values([
      {
        id: 'inv_501',
        invoiceCode: 'INV-2026-701',
        patientId: 'pat_1',
        patientName: 'Jonathan Reed',
        patientCode: 'PAT-8001',
        patientPhone: '+1 (555) 234-5678',
        items: [
          { description: 'Cardiology Senior Consultation Fee', category: 'Consultation', unitCost: 150.0, quantity: 1, amount: 150.0 },
          { description: '12-Lead Electrocardiogram (ECG)', category: 'Diagnostics', unitCost: 85.0, quantity: 1, amount: 85.0 },
          { description: 'Complete Blood Count (CBC)', category: 'Laboratory', unitCost: 45.0, quantity: 1, amount: 45.0 },
          { description: 'Telmisartan 40mg (30 Tabs)', category: 'Pharmacy', unitCost: 25.0, quantity: 1, amount: 25.0 },
        ],
        subtotal: 305.0,
        discount: 20.0,
        tax: 14.25,
        insuranceCoverage: 200.0,
        paidAmount: 99.25,
        balanceDue: 0.0,
        status: 'PAID',
        paymentMethod: 'INSURANCE',
        transactionReference: 'TXN-BCBS-99182',
        dueDate: '2026-03-30',
      },
      {
        id: 'inv_502',
        invoiceCode: 'INV-2026-702',
        patientId: 'pat_2',
        patientName: 'Eleanor Vance',
        patientCode: 'PAT-8002',
        patientPhone: '+1 (555) 345-6789',
        items: [
          { description: 'ICU Cardiac Bed Charge (Per Day)', category: 'Room Charge', unitCost: 1200.0, quantity: 2, amount: 2400.0 },
          { description: 'Continuous Cardiac & Oxygen Monitoring', category: 'Nursing', unitCost: 350.0, quantity: 2, amount: 700.0 },
          { description: 'Cardiac Biomarker Panel & ABG', category: 'Laboratory', unitCost: 320.0, quantity: 1, amount: 320.0 },
          { description: 'IV Inotropic & Antiplatelet Therapy', category: 'Pharmacy', unitCost: 480.0, quantity: 1, amount: 480.0 },
        ],
        subtotal: 3900.0,
        discount: 100.0,
        tax: 190.0,
        insuranceCoverage: 3000.0,
        paidAmount: 500.0,
        balanceDue: 490.0,
        status: 'PARTIALLY_PAID',
        paymentMethod: 'CREDIT_CARD',
        transactionReference: 'TXN-CC-882103',
        dueDate: '2026-04-05',
      },
      {
        id: 'inv_503',
        invoiceCode: 'INV-2026-703',
        patientId: 'pat_3',
        patientName: 'Marcus Aurelius Sterling',
        patientCode: 'PAT-8003',
        patientPhone: '+1 (555) 456-7890',
        items: [
          { description: 'Emergency Triage & Resuscitation Bay', category: 'Emergency', unitCost: 450.0, quantity: 1, amount: 450.0 },
          { description: 'Emergency ABG & D-Dimer Test', category: 'Laboratory', unitCost: 210.0, quantity: 1, amount: 210.0 },
        ],
        subtotal: 660.0,
        discount: 0.0,
        tax: 33.0,
        insuranceCoverage: 500.0,
        paidAmount: 0.0,
        balanceDue: 193.0,
        status: 'UNPAID',
        dueDate: '2026-04-02',
      },
    ]);

    // 9. Inventory
    await db.insert(inventory).values([
      {
        id: 'inv_item_1',
        itemCode: 'MED-TEL-40',
        itemName: 'Telmisartan 40mg Tablets',
        category: 'Antihypertensives',
        stockQuantity: 450,
        unit: 'Tablets',
        reorderLevel: 100,
        unitPrice: 0.85,
        supplier: 'Novartis Pharma Distributors',
        batchNumber: 'B2026-901',
        expiryDate: '2027-11-30',
        location: 'Rack A-04, Shelf 2',
        status: 'IN_STOCK',
      },
      {
        id: 'inv_item_2',
        itemCode: 'MED-ATO-10',
        itemName: 'Atorvastatin 10mg Tablets',
        category: 'Statins / Lipid Lowering',
        stockQuantity: 42,
        unit: 'Tablets',
        reorderLevel: 80,
        unitPrice: 0.65,
        supplier: 'Pfizer Health Inc',
        batchNumber: 'B2026-442',
        expiryDate: '2027-08-15',
        location: 'Rack A-02, Shelf 1',
        status: 'LOW_STOCK',
      },
      {
        id: 'inv_item_3',
        itemCode: 'MED-AMOX-500',
        itemName: 'Amoxicillin 500mg Capsules',
        category: 'Antibiotics',
        stockQuantity: 620,
        unit: 'Capsules',
        reorderLevel: 150,
        unitPrice: 0.40,
        supplier: 'Sandoz Generic Corp',
        batchNumber: 'B2026-118',
        expiryDate: '2028-01-20',
        location: 'Rack B-01, Shelf 3',
        status: 'IN_STOCK',
      },
      {
        id: 'inv_item_4',
        itemCode: 'SUP-IV-09NS',
        itemName: '0.9% Normal Saline IV Solution 500ml',
        category: 'IV Fluids & Infusions',
        stockQuantity: 18,
        unit: 'Bags',
        reorderLevel: 50,
        unitPrice: 4.50,
        supplier: 'Baxter Healthcare',
        batchNumber: 'IV-99210',
        expiryDate: '2026-12-31',
        location: 'Storage Room C, Bay 2',
        status: 'LOW_STOCK',
      },
      {
        id: 'inv_item_5',
        itemCode: 'SUP-PPE-GLV-M',
        itemName: 'Nitrile Examination Gloves (Medium)',
        category: 'Consumables & PPE',
        stockQuantity: 1200,
        unit: 'Pairs',
        reorderLevel: 300,
        unitPrice: 0.15,
        supplier: 'Ansell Medical',
        batchNumber: 'GLV-8819',
        expiryDate: '2029-05-31',
        location: 'Central Store - Bin 12',
        status: 'IN_STOCK',
      },
      {
        id: 'inv_item_6',
        itemCode: 'MED-INSU-R',
        itemName: 'Regular Human Insulin 100 IU/ml Vial',
        category: 'Endocrinology & Diabetes',
        stockQuantity: 8,
        unit: 'Vials',
        reorderLevel: 25,
        unitPrice: 18.0,
        supplier: 'Novo Nordisk',
        batchNumber: 'INS-4011',
        expiryDate: '2026-09-30',
        location: 'Cold Storage Ref #2',
        status: 'LOW_STOCK',
      },
    ]);

    // 10. Beds
    await db.insert(beds).values([
      {
        id: 'bed_101',
        bedNumber: 'ICU-Bed-01',
        ward: 'Cardiothoracic ICU',
        floorNumber: 4,
        status: 'AVAILABLE',
        dailyRate: 1500.0,
      },
      {
        id: 'bed_102',
        bedNumber: 'ICU-Bed-02',
        ward: 'Cardiothoracic ICU',
        floorNumber: 4,
        status: 'OCCUPIED',
        patientId: 'pat_2',
        patientName: 'Eleanor Vance',
        admittedAt: '2026-03-28 08:30',
        dailyRate: 1500.0,
      },
      {
        id: 'bed_103',
        bedNumber: 'GEN-304',
        ward: 'General Male Ward',
        floorNumber: 3,
        status: 'OCCUPIED',
        patientId: 'pat_5',
        patientName: 'Robert Chen',
        admittedAt: '2026-03-29 11:00',
        dailyRate: 400.0,
      },
      {
        id: 'bed_104',
        bedNumber: 'GEN-305',
        ward: 'General Male Ward',
        floorNumber: 3,
        status: 'AVAILABLE',
        dailyRate: 400.0,
      },
      {
        id: 'bed_105',
        bedNumber: 'PVT-501',
        ward: 'Deluxe Private Suite',
        floorNumber: 5,
        status: 'AVAILABLE',
        dailyRate: 850.0,
      },
      {
        id: 'bed_106',
        bedNumber: 'EMG-Bay-01',
        ward: 'Emergency & Trauma Bay',
        floorNumber: 1,
        status: 'OCCUPIED',
        patientId: 'pat_3',
        patientName: 'Marcus Aurelius Sterling',
        admittedAt: '2026-03-30 14:15',
        dailyRate: 600.0,
      },
      {
        id: 'bed_107',
        bedNumber: 'EMG-Bay-02',
        ward: 'Emergency & Trauma Bay',
        floorNumber: 1,
        status: 'MAINTENANCE',
        dailyRate: 600.0,
      },
    ]);

    // 11. Audit Logs
    await db.insert(auditLogs).values([
      {
        id: 'log_001',
        timestamp: '2026-03-30 08:45 AM',
        userId: 'usr_nurse',
        userName: 'Nurse Clara Oswald',
        userRole: 'NURSE',
        action: 'VITALS_RECORDED',
        module: 'NURSING',
        details: 'Recorded baseline vitals for Patient PAT-8001 (BP 138/88, HR 76, SpO2 98%)',
        ipAddress: '10.0.4.112',
        severity: 'INFO',
      },
      {
        id: 'log_002',
        timestamp: '2026-03-30 09:30 AM',
        userId: 'usr_labtech',
        userName: 'Sophia Patel',
        userRole: 'LAB_TECH',
        action: 'CRITICAL_LAB_FLAG',
        module: 'LABORATORY',
        details: 'Critical Alert generated: Troponin-I 1.45 ng/mL for PAT-8002 (Eleanor Vance)',
        ipAddress: '10.0.2.45',
        severity: 'CRITICAL',
      },
      {
        id: 'log_003',
        timestamp: '2026-03-30 10:15 AM',
        userId: 'usr_doc1',
        userName: 'Dr. Alexander Vance',
        userRole: 'DOCTOR',
        action: 'PRESCRIPTION_CREATED',
        module: 'E-PRESCRIPTION',
        details: 'Created prescription RX-2026-901 for Jonathan Reed with AI safety check pass.',
        ipAddress: '10.0.3.18',
        severity: 'INFO',
      },
      {
        id: 'log_004',
        timestamp: '2026-03-30 11:30 AM',
        userId: 'usr_pharmacist',
        userName: 'David Miller, RPh',
        userRole: 'PHARMACIST',
        action: 'MEDICINE_DISPENSED',
        module: 'PHARMACY',
        details: 'Dispensed Telmisartan 40mg for RX-2026-901. Stock inventory updated.',
        ipAddress: '10.0.5.80',
        severity: 'INFO',
      },
    ]);

    // 12. Notifications
    await db.insert(notifications).values([
      {
        id: 'notif_1',
        timestamp: '10 mins ago',
        title: 'CRITICAL ALERT: Cardiac Biomarker',
        message: 'Troponin-I 1.45 ng/mL recorded for ICU Patient Eleanor Vance (Bed ICU-02)',
        type: 'EMERGENCY',
        read: false,
        link: '/laboratory',
        targetRole: 'ALL',
      },
      {
        id: 'notif_2',
        timestamp: '25 mins ago',
        title: 'Low Stock Warning',
        message: 'Normal Saline 0.9% IV Bags down to 18 units (Reorder Threshold: 50)',
        type: 'WARNING',
        read: false,
        link: '/inventory',
        targetRole: 'PHARMACIST',
      },
      {
        id: 'notif_3',
        timestamp: '1 hour ago',
        title: 'New Emergency Patient Admitted',
        message: 'Marcus Aurelius Sterling assigned to EMG-Bay-01. Triage queue token #3.',
        type: 'INFO',
        read: true,
        link: '/reception',
        targetRole: 'ALL',
      },
    ]);

    console.log('Database seeded successfully!');
  } catch (err) {
    console.error('Error seeding database:', err);
  }
}
